[[rules]]
name = "Golang"
globs = ["*.go"]
action = "put"

[[rules.pipeline]]
exec = ["go", "fmt", "$file"]

[[rules.pipeline]]
exec = ["echo", "'Done formatting $file'"]

[[rules]]
name = "Terraform"
globs = ["*.tf", "*.tfvars"]
action = "put"

[[rules.pipeline]]
exec = ["terraform13", "fmt", "$file"]